### ISSUE TITLE
Improve "Attach to Issue" function

### ISSUE THREAD

**Issue by aaronrothschild** [mattermost/mattermost-plugin-github#124]
This was just completed by @niklabh https://github.com/mattermost/mattermost-plugin-github/pull/120

Comments from @DHaussermann are quoted below.

> @aaronrothschild I do see some opportunities to add to this further that would improve the experience. Let me know of any of this would be worth adding and I can create separate issues.
> 
> 1. When I attach a comment, I should get feedback that this was done successfully (Similar integrations post a reply with such a message and a link but, a simpler way to provide feedback wold work as well)

Yes, I've had a few instances where the confirmation is re-assuring - certainly during the first experience.  I agree with @DHaussermann , the utility of having the link referenced within the conversation is pretty critical to the long-term user experience.  Over time, without the reference to the attached issue, a critical piece of development conversations can get lost.  it also serves the dual purpose of confirming that it was successful in attaching to the issue.  I'm 4/5 we should add this before merge.

> 2. In the search results, ideally we would return the issue number in addition to the title to cover cases where there titles are similar. Though the issue numbers could overlap across multiple repos within the same list.

This request has come up from a few different customers that use the equivalent function in the Jira plugin.  Displaying the issue numbers clears ambiquity and lets the user be confident they chose the right option/value.  Not sure how much effort is involved.

> 3. This design is limited to adding comments where the user is the assignee. There would also be value in adding comments to other issues as well. Would we need a more complex design to handle cases where you select an issue and don'y have permissions to comment?

Hmmm.  Not sure about this one, could we even accomodate a scenario where we couldn't post as the user (b/c permissions)?

**Comment by hector2** [comment]
Hello! Can i work on this issue?

**Comment by aaronrothschild** [comment]
@hector2 Absolutely, let me know if you have any questions at all!

Removing "Up for Grabs" label for you.

**Comment by hector2** [comment]
Hello @aaronrothschild  !

I managed to check if the issue has locked the conversation. However, there is a problem checking if the user is blocked from the organization.

I created an organization called "GabuTest", and the owner is "gabu9". In this organization, I blocked myself (hector2).

If I check if the user is blocked (using gabu9 credentials):

curl -u "gabu9" -H "Accept: application/vnd.github.giant-sentry-fist-preview+json" https://api.github.com/orgs/GabuTest/blocks/hector2

The response is 204, it means it is blocked.

However, if I do:
curl -u "hector2" -H "Accept: application/vnd.github.giant-sentry-fist-preview+json" https://api.github.com/orgs/GabuTest/blocks/hector2

The response is 404, I guess because the user itself can't see if it is blocked on an organization.

Knowing that, what happens is:
- Github plugin configured with "gabu9" and GabuTest org,  but account connected is "hector2": it will check, with hector2 credentials, if hector2 is blocked from "GabuTest" org, getting 404 (Not blocked).
So I think there is no way of knowing it a priori. We would know if it is blocked after trying to create the issue comment.

Any ideas?

**Comment by aaronrothschild** [comment]
> Knowing that, what happens is:
> 
> * Github plugin configured with "gabu9" and GabuTest org,  but account connected is "hector2": it will check, with hector2 credentials, if hector2 is blocked from "GabuTest" org, getting 404 (Not blocked).
>   So I think there is no way of knowing it a priori. We would know if it is blocked after trying to create the issue comment.
> 
> Any ideas?

@hector2 Hmmmm.  Interesting problem.  

I think returning a genericized message may be the best we can do: `Sorry, either you don't have access to the repo {REPO_NAME} with the user {GITHUB_AUTHED_USERNAME} or it is no longer available (404)` Does that cover the situation appropriately?

cc @hanzei @DHaussermann

**Comment by hector2** [comment]
@aaronrothschild I tried creating an issue comment in a blocked org repo, and the response was "403 Forbidden" so we could even identify more accurately the problem and say something like "The issue is locked for comments/You don't have permissions to do that action" if you prefer.

**Comment by aaronrothschild** [comment]
@hector2 Excellent. the more explicit the error message, the better IMO.  I would prefer that message.
