### ISSUE TITLE
Allow excluding organisation members from subscription events 

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-github#125]
There should be an option to not post issue and PR events from organisation members. If the flag `--exclude-org-member` is provided when subscribing to a repo, events from organisation members will not trigger notification.

If not organisation is set (https://github.com/mattermost/mattermost-plugin-github/blob/master/plugin.json#L45-L48), this flag has no effect.

**Comment by enolal826** [comment]
I'd like to work on this! Thanks.

**Comment by hanzei** [comment]
That's awesome, thanks @enolal826 :tada:

**Comment by enolal826** [comment]
Hello!

Two aspects:
- Since currently no flags are supported, I've thought it'd be more convenient for the Subscription struct to have a "flags" field. What do you think?

- As of now, when subscribing there is just one field "features" supported and is supposed to be a comma-separated string, but other features are also considered:
`features = strings.Join(parameters[1:], " ")`

It means that for the command
`/github subscribe owner/repo pulls,issues anotherThing`
both "pulls,issues" and "anotherThing" would be inserted in the "feature" field. I don't know if this is something expected

Thanks!

**Comment by hanzei** [comment]
1. I would like to have the "flags" as boolean fields of in the `Subscription` struct. This way we make sure that we do the parsing of the input only once and then have all data in the struct
2. That is not expected. "anotherThing" should not go into `Features`.

Let me know, if this resolves your questions.

**Comment by enolal826** [comment]
Ok, I see flags as Subscription fields a good idea. It should also be more efficient than having it in array of strings as we won't have to iterate just to check if the flag is set. Maybe another struct SubscriptionFlags could be included.

Thanks @hanzei!
