### ISSUE TITLE
"Unread messages" button links to wrong page

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-github#15]
Clicking on the "Unread messages" button on the LHS open a list of every issue and PR where the user has been mentioned. But the number in the Mattermost UI shows the number of notification a user has. That's kind of confusing. I think the button should link to the GitHub notification screen. But I'm not sure how to filter the notification by organisation.

**Comment by jwilander** [comment]
The problem is the GitHub notification page is... lacklustre, and doesn't count unreads like the plugin does. As far as I can tell there's no filtering options on the GitHub notification page to make it match what we want.

One option I've been toying with is having that button trigger a `/github todo` instead of linking to a GH page but I'm a little undecided.

**Comment by jwilander** [comment]
Have any thoughts?

**Comment by hanzei** [comment]
> The problem is the GitHub notification page is... lacklustre, and doesn't count unreads like the plugin does. As far as I can tell there's no filtering options on the GitHub notification page to make it match what we want.

I agree. The GitHub notification page lacks function we want. I propose to just link to https://github.com/notifications. If no GitHub organisation is configured, this is completely fine. If a organisation is configured, this will show more notification then in the Mattermost interface. This is slightly annoying, but also fine in my opinion.

**Comment by hanzei** [comment]
@jwilander Thoughts on ^?

**Comment by jwilander** [comment]
Whoops, I really missed that one didn't I? Yeah I think linking to https://github.com/notifications instead makes more sense 👍
