### ISSUE TITLE
Replace GitHub usernames with Mattermost usernames in notifications

### ISSUE THREAD

**Issue by lieut-data** [mattermost/mattermost-plugin-github#176]
We already resolve the GitHub user to the Mattermost user when generating the template and posting to Mattermost -- e.g. `@saturninoabril` becomes `@saturnino.abril`, given our knowledge of the linking in the GitHub plugin:
![image](https://user-images.githubusercontent.com/1023171/72159116-15128b00-3392-11ea-965d-3b339220cd61.png)

but let's also consider doing this in the body of notifications as well, so that `@asaadmahmood`, `@marianunez` and `@lieut-data` become `@asaad.mahmood`, `@maria.nunez` and `@jesse.hallam` respectively:
![image](https://user-images.githubusercontent.com/1023171/72159102-0c21b980-3392-11ea-9a02-2aed5841b4d6.png)

Of course, if no known Mattermost user has that GitHub username, we can leave the GitHub user intact.

**Comment by levb** [comment]
The Jira plugin does it already, see https://github.com/mattermost/mattermost-plugin-jira/blob/ec8f206261f3b96045f58378b70469333538aac7/server/webhook.go#L145

**Comment by agarciamontoro** [comment]
I would like to work on this one.

**Comment by agarciamontoro** [comment]
I am planning to solve this as follows:

1. Add a new function to `funcMap` in `template.go` that receives a string and returns that same string with all the GitHub usernames resolved to their assigned Mattermost usernames, if any. If no Mattermost username is found, the GitHub username will remain unchanged. This function will be really similar to the one @levb pointed to, [`replaceJiraAccountIds`](https://github.com/mattermost/mattermost-plugin-jira/blob/ec8f206261f3b96045f58378b70469333538aac7/server/utils.go#L101-L121).
2. Add unit tests for this function in `template_test.go` so we can make sure it resolves all mapped GitHub usernames.
3. Modify all templates that call the `.GetBody` function, piping that body into the new registered function. The templates to modify are:
    - `newPR`
    - `newIssue`
    - `issueComment`
    - `pullRequestReviewEvent`
    - `newReviewComment`
    - `commentMentionNotification`
    - `commentAuthorPullRequestNotification`
    - `pullRequestReviewNotification`
4. Adapt the tests in `template_test.go` so that we test the changes in the body both when there is a `gitHubToUsernameMappingCallback` registered and when there is not.

Some notes:

- The titles of the issues and pull requests may contain usernames, but they do not trigger notifications to the mentioned GitHub users, so I would let the usernames there unchanged.
- I have not found any public documentation about the requirements that a valid GitHub username must fulfill, so I am using the error messages returned in https://github.com/join (inspired by https://github.com/shinnn/github-username-regex); namely:
  1. The username must be between 1 and 39 characters long.
  2. The username may only contain alphanumeric characters or single hyphens (i.e., not two adjacent hyphens, as in `@wrong--username`).
  3. The username cannot begin or end with a hyphen.
- I see no way of both checking the length and assuring that there are not two adjacent hyphens without lookaheads, so I am proposing to only check constraints `ii` and `iii` but not `i`. In the rare case that we would match a string with more than 39 characters, we would not have any mapping to a Mattermost user, so the string will remain unchanged.
- When writing comments in GitHub, the usernames are converted into mentions unless they are prepended by an alphanumeric character (this discards things such as `email@gmail.com`), an underscore (_) or a backtick (`).
- Following the two previous comments, the proposed regular expression would be `[^_\x60[:alnum:]]@[[:alnum:]](-?[[:alnum:]]+)*`, where `\x60` is the backtick character.

I have already started working on this, but please tell me if you would like me to implement something in a different way.

**Comment by lieut-data** [comment]
Thanks again, @agarciamontoro!
