### ISSUE TITLE
Mentions in the description of a PR/Issue should send a DM to the user mentioned

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#245]
Mentions in comments currently send DMs to the person mentioned, but when mentioned in the description of a PR/Issue, the user does not receive a DM. The task here is to make sure any connected user that is mentioned in the description receives a DM notification in Mattermost.

**Comment by nickmisasi13** [comment]
I'd like to take a look at this one

**Comment by hanzei** [comment]
Thanks @nickmisasi13. Let me know, if you have any questions.

**Comment by nickmisasi13** [comment]
Just want to Clarify a few things:
1. The task here is to make sure any connected user that is mentioned in the description receives a DM notification in Mattermost.
I've been working off the assumption that we want the connected user to be sent a DM regardless of if they are subscribed to the project the PR belongs to? 
2. In the event of a PR being posted to a project you are subscribed to, you would already be receiving a notification for the PR. Do we want a second notification to come through because of the mention? Or should it be smart enough to only send one notification? In this case, which notification takes precedence?

**Comment by mickmister** [comment]
> I've been working off the assumption that we want the connected user to be sent a DM regardless of if they are subscribed to the project the PR belongs to?

@nickmisasi13 The GitHub plugin allows subscribing to notifications related to a specific GitHub organization. The events should already we fairly filtered out using this logic when you get mentioned in a comment, for example. So the logic there is probably useful here.

> Do we want a second notification to come through because of the mention?

@nickmisasi13 Separate notifications is fine
