### ISSUE TITLE
Connect one repo instead of an organization

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-plugin-github#25]
Use case from customer:

Since we are connecting back to a Mattermost channel, and orgs can span many teams, being able to provide the hook at the repo level would be very helpful.

This might need an OAuth for each repo connection, but not sure.

**Comment by jwilander** [comment]
You can already do this, just set up your GitHub webhook from the repo instead of the org and you'll only get events (notifications and subscriptions) about that repo or however many repos you create webhooks for

The reminder and /github todo will still search the whole org but those only show stuff you're assigned to so it shouldn't matter

You also cannot set up OAuth per repo, that doesn't make any sense. OAuth apps are not tied to an organization/repo when connecting, they're tied to the end user

**Comment by jasonblais** [comment]
Ah, that makes a lot of sense.

I've
1. opened an FAQ item for README that covers this question. If you think that's unnecessary, it can be closed https://github.com/mattermost/mattermost-plugin-github/pull/27/
2. asked the customer to post in the GitHub plugin channel on pre-release (they had a few other questions), so they can talk to you and other plugin maintainers directly 👍
