### ISSUE TITLE
mattermost and github

### ISSUE THREAD

**Issue by gstlouisgit** [mattermost/mattermost-plugin-github#410]
I am trying to learn how to use this integrated github in mattermost.  I was kind of hoping I could see my issues list that I could maybe action and update from the mattermost sidebar that shows the list of github stuff.  I don't think this is possible

But I do see assignments.  How does this work?  I create an issue and assigned myself, but it did not populate anything on my github left bar and if I try /github todo I get empty fields.  What am I doing wrong?

thanks
Guy

**Comment by larkox** [comment]
I can see two reasons why you might not be seen the assignments.
- Have you refreshed the information? (either by refreshing the page or hitting the refresh button alongside the github buttons)
- Are you assigning yourself to a private repo? Private repos need you to connect in a special way (`/github connect private` instead of `/github connect`)

**Comment by gstlouisgit** [comment]
yes that seems to be it!
/github disconnect then /github connect private.  Thank you
