### ISSUE TITLE
GitHub 2.1.0 - Unable to slect repo from create issue modal  

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-github#491]
When trying to select a repo from the Create Issue modal. A JS error occurs and the repo cannot be selected.

This happens for any repo I attempt to select (Public or Private)

Steps:
- Install and configure GitHub 2.1.0 
- Enable the plugin
- Connect a test user
- Open the create modal either by selecting create from a post or by typing `/github iccue create`
- Open the repo drop down list and select any repo

**Observed**
![image](https://user-images.githubusercontent.com/35588783/136097112-564cbb23-0181-4863-aeab-b479ced0910f.png)
![image](https://user-images.githubusercontent.com/35588783/136097151-baca7ef7-4a30-4707-9934-66a86ed3833f.png)

I'm not sure if the second error is related it does not occur every time. Please disregard if it's not relevant.

**Comment by DHaussermann** [comment]
@hanzei note that this got into master somehow and blocks the release. This area was touched by https://github.com/mattermost/mattermost-plugin-github/pull/447 but to me the error has no obvious reason to be related.

**Comment by hanzei** [comment]
Thanks for catching this, Dylan. This is indeed a regression caused by https://github.com/mattermost/mattermost-plugin-github/commit/aa96cfc8d4db0e4f14f7c078d1af408a3f9be9b3.

I will submit a PR to revert the changes in order to unblock the release.

@dipak-demansol I'm wondering if you tested the scenario that Dylan pointed out. Are you now able to reduce the issue?

**Comment by sanjaydemansol** [comment]
@DHaussermann @dipak-demansol I am unable to reproduce this issue so far. any leads?

https://user-images.githubusercontent.com/85980820/136250819-fde392f7-b74d-4511-bdd5-469cc8b2d967.mp4

**Comment by DHaussermann** [comment]
@sanjaydemansol that's very curious. Aside from making sure you have the `v2.1.0` PR deployed - 0/5 Maybe try in a browser session with fresh cache. 
If it helps, I reproduced this on multiple servers including the sandbox here https://demansol-sandbox.test.mattermost.cloud where I also deployed the 2.1.0 version bump RC and I see the issue here as well. DM me if an invite to this server would be helpful.

**Comment by sanjaydemansol** [comment]
@DHaussermann , @hanzei @dipak-demansol  you are right, this is indeed caused by aa96cfc8d4db0e4f14f7c078d1af408a3f9be9b3,
but since it is what was requested by the author of Issue: 

> We are using `option.label` as an option's unique identifier because currently `option.label` and `option.value` are the same in each option in the case of the GitHub repo selector component. We should be using `option.value` in order to follow common conventions and to be consistent with the other plugins.
Ref. #263 @mickmister

**_which is not the case:_**
![Screenshot_3](https://user-images.githubusercontent.com/85980820/136422085-1d4a0908-12bb-4caf-b792-5e46d657abc8.png)
any opinion, what to do next?

**Comment by dipak-demansol** [comment]
> Thanks for catching this, Dylan. This is indeed a regression caused by [aa96cfc](https://github.com/mattermost/mattermost-plugin-github/commit/aa96cfc8d4db0e4f14f7c078d1af408a3f9be9b3).
> 
> I will submit a PR to revert the changes in order to unblock the release.
> 
> @dipak-demansol I'm wondering if you tested the scenario that Dylan pointed out. Are you now able to reduce the issue?

yes, but forgot to reply here .
