### ISSUE TITLE
when the github issue posted in the mattermost channel via issue-create event then some issue-data is changed in the mattermost post.

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-plugin-github#566]
#### Summary
issue some data is changed in the mattermost when they posted via issue-creation event.

#### Steps to reproduce
post this data as `; <level>` and report it in the github issue and check that issue event post in the mattermost channel and you will see there different data, you can also check the video.

#### Expected behavior
data should be visible same to same in the mattermost channel

#### Observed behavior (that appears unintentional) 

https://user-images.githubusercontent.com/89907719/171009560-fda23964-71da-4b89-92e1-a32b54c437f0.mov

**Comment by Kshitij-Katiyar** [comment]
Hey @dipak-demanso @wiggin77l, I looked into this issue and tried reproducing it, and here are the steps I followed:
- Subscribed to a dummy repo
- Created two issues by copying the description of the issues you showed in the video i.e [autolink 195](https://github.com/mattermost-community/mattermost-plugin-autolink/issues/195) [autolink 194](https://github.com/mattermost-community/mattermost-plugin-autolink/issues/194)
- Checked the subscription post on mattermost channel.
Here is the screenshot of mattermost post and github issue
![image (3)](https://github.com/user-attachments/assets/4c3d7560-3dab-4bef-acdc-92c76828c9d6)
![Screenshot from 2024-09-27 10-47-43](https://github.com/user-attachments/assets/7e9a9e28-782b-4709-90a2-a3023f43c826)
---
![image (4)](https://github.com/user-attachments/assets/a3beb7ca-8f4a-42c5-bcb2-9032eb178730)
![Screenshot from 2024-09-27 10-45-40](https://github.com/user-attachments/assets/575681a5-cab3-4513-9398-bcd6d375c6eb)

The issues you have reported might have been fixed in any of the previous PRs. Let me know if you are still facing these issues.
