### ISSUE TITLE
Ephemeral message "Not able to get list of webhooks" after creating a subscription

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#732]
I'm seeing this error message after creating a subscription

> Not able to get the list of webhooks. This feature is not available for subscription to a user.

I'm thinking it may be better to not return an error in this case, and just show the subscription post instead

<img width='600px' src='https://github.com/mattermost/mattermost-plugin-github/assets/6913320/ff2be51a-2af1-4d00-a529-a6f1b829145e'/>

**Comment by ayusht2810** [comment]
@mickmister This error is returned when no webhook is configured while creating a subscription from the line. https://github.com/mattermost/mattermost-plugin-github/blob/6cc3429a497c27acc2707e9b4707b28ee210749f/server/plugin/command.go#L459 and this was done due to the issue https://github.com/mattermost/mattermost-plugin-github/issues/378 to remind the user that a webhook must be set up. Do we need to update this, or is what we have currently fine?

**Comment by mickmister** [comment]
> This error is returned when no webhook is configured while creating a subscription from the line.

@ayusht2810 I think what's actually happening here is that I don't have permissions to browse the webhooks in our GitHub org, which is expected. So we should just not show this error in this case
